# Version
version: 0.0.1+build.{build}

# Only build master
branches:
  only:
    - master

# Patch AssemblyInfo.fs
assembly_info:
  patch: true
  file: AssemblyInfo.fs
  assembly_version: "0.0.1"
  assembly_file_version: "0.0.1"
  assembly_informational_version: "{version}"

# Build the main solution, publish nuget
build:
  project: SemVer.sln
  publish_nuget: true

# Build in AnyCPU|Release
platform: AnyCPU
configuration: Release

# Restore nuget packages before build
before_build:
  - nuget restore SemVer.sln

# Deploy any packages to nuget.org
deploy:
  provider: NuGet
  server:
  api_key:
    secure: Thb6XVoqRBj6fgRvwew4vcVtyxU4lM4IJE3iLJN7rX9srMydbI/O5LgKgEHeV2Xj
  artifact: /.*\.nupkg/
