version: 0.0.{build}
branches:
  only:
    - master
assembly_info:
  patch: true
  file: AssemblyInfo.fs
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
build:
  project: SemVer.sln
  publish_nuget: true
before_build:
  - nuget restore SemVer.sln
deploy:
  provider: NuGet
  server:
  api_key:
    secure: Thb6XVoqRBj6fgRvwew4vcVtyxU4lM4IJE3iLJN7rX9srMydbI/O5LgKgEHeV2Xj
  artifact: /.*\.nupkg/
