# Version
version: 0.0.1+build.{build}

# Patch AssemblyInfo.fs
assembly_info:
  patch: true
  file: AssemblyInfo.fs
  assembly_version: "0.0.1"
  assembly_file_version: "0.0.1"
  assembly_informational_version: "{version}"

# Deploy any packages to nuget.org
deploy:
  provider: NuGet
  server:
  api_key:
    secure: Thb6XVoqRBj6fgRvwew4vcVtyxU4lM4IJE3iLJN7rX9srMydbI/O5LgKgEHeV2Xj
  artifact: /.*\.nupkg/
